### PR TITLE
Adds search box to profile crew page (copied from #161)

### PR DESCRIPTION
**Pull request by ineffyble**
_This is @ussjohnjay's PR copied into a local branch to enable CloudFlare PR testing._

This adds a search box to the crew roster component on player tools and profiles, but there's a lot going on under the hood in this one:

This refactors searchabletable and profile_crew to use React hooks. Among other benefits, this will allow us to more easily tie state data to session, thus letting us store form data on any page that needs it. You can see it in action right now with the refactored profile crew page.

A new storage utils file holds the logic for the storage hook. It uses sessionStorage by default, but it should work with localStorage too. Hopefully this will be fully compatible with other components, but some may need to be refactored first.

Moved some logic to searchabletable and the new crewsearch utils file, so that searchabletable can handle sorting and filtering by search string for more components (in this case, profile_crew but hopefully crew retrieval down the line). The main index and items page were updated to be compatible with these changes.

The profile crew component now has a checkbox to toggle frozen crew.

But really this is all just to see if I can create a new Cloudflare test page from a PR.

### CODE REVIEW

**Comment by ineffyble** [comment]
@ussjohnjay I'm not seeing any change to the Crew tab in Player Tools at the above deployed link.

Is the issue with the CloudFlare deploy or the code?

**Comment by ussjohnjay** [comment]
@ineffyble Thanks for creating a new branch for this. I just tried it out. The CloudFlare test page works for me, with the searchbox appearing on the crew player tool as expected.

**Comment by ineffyble** [comment]
@ussjohnjay can you take a screenshot? Maybe I'm missing something.

**Comment by ussjohnjay** [comment]
Here's what you should see here:
Screen Shot 2021-04-03 at 14 00 14

This is the current crew profile page, without the searchbox:
Screen Shot 2021-04-03 at 14 01 39

**Comment by ineffyble** [comment]
@ussjohnjay If you can resolve the conflicts I'll merge.

**Pull request merged**
