### PR TITLE
revert bad config preventing datacore from building

### PR DESCRIPTION
**Pull request by nmoschkin**
Revert config change preventing successful build.

### CODE REVIEW

**Comment by joshurtree** [comment]
Not sure why the Gatsby update broke things. It still builds locally and the logs are unhelpful. They simply say "operation cancelled". The build time is longer so could it be a timeout issue?

The commit currently introduces three unused packages. To keep things clean we  should only be reverting Gatsby to the old version.

**Comment by nmoschkin** [comment]
I have reverted the package.json and the yarn.lock to a previous master-based branch's version.

The issue is not that it is simply the package.json file, but the yarn.lock that changed, too.  And that is too onerous to manually revert.  Also... the project does not currently "build anew" without the yarn.lock that's in there.

Like, we can't build it with just a bare package.json file, something is preventing that.

**Review by joshurtree — COMMENTED** [review]
Now "gatsby-transformer-remark" is being bumped back version 3?

**Comment by nmoschkin** [comment]
Yeah. So. I do not have the original package.json and yarn.lock files that contained the updated gatsby-transformer-remark 5.25.1.  I put it back in, and pushed the change.  However, I should let you know there is a warning that 5.25.1 is incompatible with gatsby 3.0.0.

What version of NodeJS are you building locally with?

**Comment by nmoschkin** [comment]
Also.  A while back, I was actually attempting to integrate the gatsby version bump.  I have not been successful, and while attempting to resolve the gatsby versioning locally, I was told by gatsby that the GraphQL queries were in a deprecated format.

**Review by joshurtree — APPROVED** [review]
Approving now. Will continue discussion in Discord.

**Pull request merged**
