### PR TITLE
New experimental voyage calculator

### PR DESCRIPTION
**Pull request by ussjohnjay**
Here's a new experimental voyage calculator, written in plain JS and using a very different algorithm. The good news is that in most of my tests so far, the results are on par with or better than the current "classic" calculator and they're delivered reliably quickly. The bad news is that the new spinner doesn't spin quite so good because plain, single-threaded JS blocks the UI as the calculator is doing its thing.

I put together a new player tools page that allows you to run each calculator side by side and compare the results. This will also reassess any classic results with the runtime estimate you'd get by feeding the numbers into the bot, which is more pessimistic than the website's classic estimate.

This branch is only meant for testing. It's nowhere near ready for production and requires lots and lots of player data first. Please compare as many voyages as you can and report any bugs, inconsistencies, and times where the experimental recommendations are worse than the classic.

Thanks!

### CODE REVIEW

**Comment by flash82** [comment]
> The bad news is that the new spinner doesn't spin quite so good because plain, single-threaded JS blocks the UI as the calculator is doing its thing.

That's what web workers are for. They allow you to cut out a piece of JS and separate it to its own thread, which works entirely in the background and doesn't block the UI from updating. The entire time the web worker is active, you can communicate with it through a bi-directional message system; not only to send data at the start and receive the final result (in string form, so as serialized data) but also to get regular progress updates to update the UI and inform the user.

The current IAP calculator, as implemented here in datacore, already uses this method to both keep the UI from freezing and post regular updates of a better voyage line-up while it continues to work. We can see that now thanks to the spinner replacing the greyed-out area.

Here's where the worker is initialized and where progress/completion messages are handled:
https://github.com/stt-datacore/website/blob/master/src/utils/voyageutils.ts#L250

And here's the worker part, where those are posted:
https://github.com/stt-datacore/website/blob/master/src/wasm/wasmWorker.js#L8

That can be built manually using the same process as we're using already, but there's also a [react-webworker](https://github.com/async-library/react-webworker) that could help, as it automates a few things.

**Comment by ussjohnjay** [comment]
Thanks, that makes perfect sense. I'll be honest that I never understood how the current calculator was implementing the web worker and I didn't try to reuse any of it because it seemed specific to its own usage. 

The react-webworker looks very promising, though. Much more straightforward. As I mentioned elsewhere, it's not the lineup generation but the voyage runtime estimation that's the real bottleneck. If we could push that part of the calculation to a web worker, that alone might boost the performance. I'll see what I can do about getting that module running with the experimental calculator.

One last note, re: my modifying of the current worker code. I don't think the abort button as implemented is actually cancelling the web worker, so much as it's hiding the spinner while the process continues in the background. You can see this for yourself if you abort really early into a calculation. The spinner just pops up again if the worker has more results. My hacky fix was to keep the worker in state and then terminate it when the abort button is clicked. If someone with a better understanding of web workers can verify the issue and push a real fix to the site, that would be great.

**Comment by flash82** [comment]
>  I'll be honest that I never understood how the current calculator was implementing the web worker

The current implementation uses the [webpack worker loader](https://webpack.js.org/loaders/worker-loader/) instead of pure JS.

**Comment by ussjohnjay** [comment]
Closing this for now. Will resubmit after #153 is done. Hopefully a future version of this on a CloudFlare page will make testing easier, plus I plan to include additional logging options.

**Pull request closed without merging**
