### PR TITLE
Embed finish time odds for running voyages

### PR DESCRIPTION
**Pull request by joshurtree**
I've created a slightly modified version of Chewable's voyage calculator so that it accepts parameters in the url. This code then puts a link at the top of the voyage calculator which autofills the details of your current voyage into the calculator.

### CODE REVIEW

**Comment by ussjohnjay** [comment]
It's great that you created a version of the Chewable calculator that takes input, as that has been sorely missing. However, would it be okay with you to keep this particular functionality on DataCore without having to go to Codepen at all?

As part of my experimental voyage calculator, I was able to create a worker module for the Chewable calculator, which takes inputs much like the pairs you collect in this. You can kind of see it here (ignore everything vector related):
https://github.com/stt-datacore/website/blob/1f5e4a4c55c10139d037d9746bfee95d8bccae82/src/workers/chewableWorker.js

I have a more updated and simplified version that I was planning to submit as a standalone. You could then pass your inputs to it and directly get the estimated duration of an ongoing voyage to display on DataCore. We could still link to your Codepen for users who want to see the details for themselves. What do you think?

A couple other questions, which I'd love to get your thoughts on:

1) Is proficiency dependent on skillOdds? I've just been calculating prof as a percentage of total skill and I hadn't considered that it might be also related to skillOdds.

2) Have you run into cases where voyage_duration from voyageData is inaccurate? There are times (maybe when a dilemma is waiting to be resolved?) that the voyage_duration value is wildly off from the actual voyage runtime, but I haven't been able to fully figure out why yet. When it's wrong, it leads to voyage estimations being improbably optimistic.

**Comment by ussjohnjay** [comment]
I just posted a draft of the Chewable Estimator worker #154. I suggest merging that into any branch that can use it (and changing it as you see fit).

And here I tweaked your setupVoyageLink to pass the variables into the worker and then store the estimate result in state:
[voyagecalculator_iap.tsx.txt](https://github.com/stt-datacore/website/files/6200242/voyagecalculator_iap.tsx.txt)

It's not very pretty, but hopefully it shows how I think this is supposed to work. Again, please change it as necessary or tell me what I'm missing.

One other note, I suggest adding a check to see if a voyage has started before trying to create the Codepen link. I would also move the logic into componentDidMount, because I think it only needs to be generated once and not on every render.

**Comment by joshurtree** [comment]
I've changed it to an embeded component which shows up if a started voyage is detected. It could also be used with calculated voyages this way as well. I think a chart of odds/time would look good (looks like chewable had one but its never worked for me). This would mean monkeying around with ChewableWorker and looking up how to use nivo. So I will probably leave that for another PR.

**Comment by ussjohnjay** [comment]
I like this solution, a separate component showing the ongoing estimate when an active voyage is detected, while hiding the calculator form by default. I didn't realize Chewable had charts but I'm intrigued by one day having that possibility here.

We can eventually expand your new component to show some pending rewards, too. If I may suggest passing the whole `voyageData` object to the `<VoyageStats>` component instead (thus letting the subcomponent calculate aggregate skills and variance to pass to the worker), that might make it easier to add new things to `<VoyageStats>` down the line.

Can you please copy the chewable.js and chewableWorker.js from #154 into your branch's workers subdirectory? The worker you're using here is one of my older versions, which doesn't actually factor in the elapsed voyage runtime into its calculation; it just gives an estimate as if the voyage is starting from scratch. The revised worker in #154 corrects this and it also addresses an exception thrown by the react-refresh-webpack-plugin. You should be able to copy in the updated files without having to change anything else.

Two others questions that aren't specific to what you've done here, but might be useful to consider:

1) What should the voyage tool show when it detects a voyage that's already on its way home (i.e. `voyage[0].state === 'recalled'`)? Right now it just shows the form, which is misleading because you can't actually send out another voyage yet.

2) Should we apply the DataCore bot's pessimism to estimates on the site? I think the consensus is that the current calculator on the DataCore site is too optimistic. We can use the default Chewable estimate, but that makes it inconsistent with the bot, even though both are using the same algorithm.

**Comment by joshurtree** [comment]
I've added rewards and the updated worker. Other possible additions are the crew used and aggregate scores but that would result in a lot for one page. I'm thinking making each segment collapsible with different configurations of visible and collapsed based on the state of the voyage might be a way to go. So during a voyage rewards are available but collapsed. Then when it is recalled we collapse crew and aggregate scores leaving rewards as the primary component.

On the second question, I don't think that the calculator is overly optimistic. It only predicts what happens 50% of the time but people get disappointed when it doesn't happen most of the time. Its more a difference in expectations. It is the reason you can make money off poker if you understand probability.

Having said that another use of this component is to provide tailored results independent of the calculator used. So instead of reporting the results of the IAP calculator directly we could use just the crew suggested by it and feed it through the VoyageStats component instead. Likewise with your calculator and any others (I have an idea for one based on maximising probability of reaching a dilemma). This could be synced up with the bot so that everything in the ecosystem agrees with each other.

**Comment by ussjohnjay** [comment]
First things first, nice job getting the images to work with the rewards table. The image names from the player data were maddeningly inconsistent here.

I like how your rewards table looks on desktop, but I should note that it doesn't render very well on mobile:
Screen Shot 2021-04-03 at 13 25 30

One request: can we sort the rewards so that the items are grouped a little better, perhaps even with the more interesting stuff listed first (e.g. crew, honor, chronitons)? I tried to do some item sorting like this before, if it's useful:

```
rewards.loot.sort((a, b) => {
	if (a.type == b.type && a.item_type === b.item_type && a.rarity == b.rarity)
		return a.full_name.localeCompare(b.full_name);
	else if (a.type == b.type && a.item_type === b.item_type)
		return b.rarity - a.rarity;
	else if (a.type == b.type)
		return b.item_type - a.item_type;
	else if (a.type == 2)
		return 1;
	else if (b.type == 2)
		return -1;
	return a.type - b.type;
});
```

One last question, do you think it's necessary to show the 90% result with the other estimates? I might consider omitting that, as the other stats provide a good amount of information without being overwhelming.

Thanks for doing this. I think we're close to getting this perfect!

**Comment by joshurtree** [comment]
I've taken some code that I was going to include in the next iteration and imported it. So I have added crew details and made each section collapsable. Added some code which hopefully help it render on mobiles. I personally find the 90% datum useful as it gives you a better idea of the spread of potential durations. I have removed it from mobiles to save space though.

**Comment by ussjohnjay** [comment]
Everything looks great! I appreciate that you divided everything into sections, and especially like that we can now see the currently assigned crew. Speaking of which, I would suggest calling that first section something like "Assigned crew" or "Voyage lineup" as "Crew" is kind of ambiguous and I originally clicked it expecting to see the crew I was getting as rewards. Additionally, it would be great if you could include honor in the rewards summary line (alongside # of crew and chrons). Neither of these are big deals, just tiny enhancements.

If you can add in the check from #162, I'll give this an approving review.

**Review by ineffyble — APPROVED** [review]
Merging based on discussion

**Pull request merged**
