### PR TITLE
Adds faction information page in player tools

### PR DESCRIPTION
**Pull request by joshurtree**

### CODE REVIEW

**Comment by ussjohnjay** [comment]
Pretty neat. Just to be clear, when it tells me, "you need to run 437 shuttles at 14%", does that mean I should assemble a shuttle lineup with a success chance less than 14%? In any case, it's going to take me forever to tank any faction.

One request: I would prefer that the faction icon URLs not be inserted into the stripped player data. Our practice should be to limit stripped data to things that are specific to a given player, whenever possible. Because the faction icons are universal and there aren't that many of them, I think it would be better to define the URLs as a constant in the component (or maybe the config file if you anticipate using these images again elsewhere).

Other than that, everything looks good to me.

**Comment by joshurtree** [comment]
I've changed it to a local array. Even when using level 1 crew with no matching skills, 14% is the minimum that you can run shuttles at.

**Comment by AlexCPU** [comment]
I like it, seems to work well.  I think below the table we should include a description of what tanked shuttles are, or we'll end up fielding that question all the time.  If you can add that in, I'll approve and merge.

**Comment by AlexCPU** [comment]
I was just about to merge this, but looking at the CF Pages test site, I'm not seeing the faction tab anymore.  Any idea what broke?

**Review by ussjohnjay — APPROVED** [review]
It looks like the new factions tab wasn't re-added quite properly when @joshurtree tried to merge my changes to playertools from #201. I fixed that here and made a couple of quick changes while I was double-checking everything (fixing a "Despised" typo and adding map index to table rows in factions.tsx).

Everything looks good to me now.

**Pull request merged**
