### PR TITLE
Add a mobile Sidebar (with hamburger menu)

### PR DESCRIPTION
**Pull request by TemporalAgent7**
This replaces the top fixed menu items with a hamburger that opens them in a sidebar on mobile screens (and small width browser windows).

Also consolidated the use of Containers for main page content to the Layout, and fixed a small issue with Sunburst charts by pinning the dependency to 0.64.

Change can be tested at http://test.datacore.app/ .

### CODE REVIEW

**Comment by ussjohnjay** [comment]
Thank you so much for this! This is a terrific solution for mobile responsiveness.

Just a few notes:
1) With the viewport being fixed now, we can't see or access everything on elements that are too wide, specifically tables and tabpane menu items (on player tools and profiles). Enabling horizontal scrolling on overflow should fix this for the tables, but I'm not sure if that's easy to do with the panes (i.e. enabling scrolling only on the menu items, while keeping the content responsive).

2) "About" is listed twice in the sidebar, as a main section and as a subitem under "All other pages." Are both necessary?

3) This is really minor, but on dark mode, the dark gray text of the subitems (like "Image list (fast)" and "Complete (slow") is a little hard to read on the gray sidebar. It could be just me, but I think it could use a little more contrast. The white text of the main items looks great and everything in light mode looks good, too.

Otherwise I really like this!

**Comment by TemporalAgent7** [comment]
> Thank you so much for this! This is a terrific solution for mobile responsiveness.
> 
> Just a few notes:
> 
> 1. With the viewport being fixed now, we can't see or access everything on elements that are too wide, specifically tables and tabpane menu items (on player tools and profiles). Enabling horizontal scrolling on overflow should fix this for the tables, but I'm not sure if that's easy to do with the panes (i.e. enabling scrolling only on the menu items, while keeping the content responsive).
> 2. "About" is listed twice in the sidebar, as a main section and as a subitem under "All other pages." Are both necessary?
> 3. This is really minor, but on dark mode, the dark gray text of the subitems (like "Image list (fast)" and "Complete (slow") is a little hard to read on the gray sidebar. It could be just me, but I think it could use a little more contrast. The white text of the main items looks great and everything in light mode looks good, too.
> 
> Otherwise I really like this!

For 1, I'm not sure what you mean - can you point to a difference in behavior from the current version? I agree we need a way to make tables more responsive (or maybe scrollable), but this change shouldn't make that any worse (or better 😄 ).

For 2, that just emulates the current menu layout (About shows up twice in the regular menu too); we can hard-code an exclusion for it in the GraphQL query to apply in both places.

For 3, the problem is we'd make a change in the semantic.slate.css in a shared location which may have unintended side-effects on other UI elements, but I'll play a bit with it.

**Comment by ussjohnjay** [comment]
Screenshots don't quite convey the behavior I'm getting, but I'll try to explain. In this first screenshot, everything in the table that's to the right of "Command" is cut off, and I can't scroll left or right to control what part of the table I see, as I would expect to be able to. (By swiping on my Android, at least.)

Screen Shot 2021-03-10 at 12 36 53

Here, the voyage calculator is shown in its entirety as expected, but the menu items to reach other player tools are inaccessible if they're to the right of "Crew (mobile)". Again, I can't scroll left or right on the menu items.

Screen Shot 2021-03-10 at 12 40 58

**Comment by ussjohnjay** [comment]
Also to clarify how this is different, because the viewport isn't fixed on the current version of the site, page width is determined by the content, so when the content is too wide for the device, the mobile browser lets us scroll to see what would normally be in overflow on a fixed viewport. It's obviously not ideal, but it does have the advantage of keeping everything accessible.

(There's a notable exception for topmenu items as currently implemented, which when the content fits within the device viewport, the rightmost topmenu items are inaccessible.)

**Comment by TemporalAgent7** [comment]
> currently implemented, which when the content fits within the device viewport, the rightmost topmenu items are inaccessible.)

Thank you, that was very useful. I re-added the ability to horizontally scroll in mobile view. Updated the test website with these 3 changes: https://test.datacore.app/

**Comment by ussjohnjay** [comment]
Fantastic, everything works as expected now. Thanks again for this much-needed enhancement!

**Pull request merged**
