### PR TITLE
Various voyage calculator fixes

### PR DESCRIPTION
**Pull request by joshurtree**
Fix 100% dilemma bug. Fix voyage time bug. Adds primary/secondary sklls to voyage message.

### CODE REVIEW

**Comment by ussjohnjay** [comment]
The current duration of an existing voyage seems off with this. My voyage is at the 8hr dilemma right now (awaiting my choice in-game), but the calc says my voyage has been running for 7h 50m.

Seeing the voyage skills in the message is a nice addition. Maybe the current estimate can go in the message too?

**Comment by ussjohnjay** [comment]
I have a couple questions that aren't really related to this, but I've been meaning to ask.

1) Is it possible to move the filling of bins out of `chewable` and into `voyagestats` right before they're used to calculate percentages? Moving that loop out of chewable will speed up MVA calculation by about 20%. I don't think it will speed up the original calculator any, but it shouldn't negatively affect it either (unless I'm misunderstanding how the bins are being used).

2) I think we can avoid a fetch to ship_schematics in `voyagestats` because `voyagecalculator` always fetches it now and passes it down. Should save a little time, though I admit there might be cases for fetching it again that I'm not considering.

Again, these aren't related to the changes you've made here, but I wanted to note them as potential places for optimization and get your insights before I dig into them further.

**Comment by joshurtree** [comment]
The duration seems to be generally accurate. It might yet another bug involving dilemmas but is far more preferable to using the reported voyage duration which often just carries on counting when waiting for a dilemma response. I am happy to add the estimate to the message but seems a bit redundant as the estimate appears directly below it.

I am planning a optimization of `chewable` at  some point. Now it is doing two different jobs there is a lot of stuff in there that isn't always needed. I realised I missed a piece of code so I fixed that which should provide performance improvements.

I am also planning various improvements to the `voyagestats` component based on various comments in discord and some ideas i've had. I want to show which crew are getting a trait bonus. I will also add an icon representing the crews primary trait which will state something like 'Scroll to 3rd from top in <skill>'. I also want to integrate the citation optimiser so that crew that will would improve the voyage if cited/trained are shown. I'm torn between working on this or a new section of the website which will be called Dabo for my next major project.

**Comment by ussjohnjay** [comment]
I really like the additions you made here! Very glad to see so many requests incorporated here. I think we can still improve the way the recommendations are displayed. I have a few ideas for this, if you don't mind. I'll try to post screenshots of some potential alternatives in the next day or so.

I appreciate the attempt to implement a noBins option for MVAM as a way to address my earlier request. As I'm sure you know, the bins are actually required for voyagestats' renderChart method, so simply removing the bins from the MVAM calculation only works if we also stop showing the chart. I like the charts, so I definitely don't want to do this.

What I did instead was move the calculation of bins out of chewable (where the bins may be calculated for results that are never shown) to renderChart (so that the bins are only calculated on a shown recommendation). Of course this assumes that bins aren't needed for anything other than renderChart, so if you have plans for using them elsewhere, please feel free to revert what I did here. For what it's worth, this change does speed up MVAM calculations by about 15-20%; I thought it might also improve original calculations by a small measure, but my tests did not see any appreciable change in original calculation time, one way or the other.

I admit, I had not considered completely removing the extends options to speed up MVAM. But I think the estimates you get for potentially extending are still useful, even if MVAM has no option for optimizing for extends. As a result, I opted to set noExtends to false by default.

**Comment by ussjohnjay** [comment]
Just sent out a voyage with this and noticed a potential area for improvement. Maybe the skill popup rank should be filtered by the seat it's in. For example, right now it told me to "Select 6th crew from top in Medicine" to find Warship EMA (because he's my 6th best MED voyager overall), but he's actually being recommended for a CMD seat, so it might be more accurate for me if it said "Top" (because he is my best MED crew with CMD).

**Comment by ussjohnjay** [comment]
Okay, here are some ideas for different ways to display the recommendation. This first one is closest to what we've got now, except it breaks everything up into a simple table. The second column has the most important info, plus an icon that shows if the crew has a matching trait for that seat. The final column is the skill to use to find that crew in your roster, plus an icon if the suggested crew is frozen.

320-table-textonly

**Comment by ussjohnjay** [comment]
This second one is basically the same as the first, except it adds avatars for each crew. This obviously expands the height needed to display everything. It's not that much more, but if you're like me and want a mobile view that doesn't need any scrolling, this may be an issue:
 
320-table-withavatars

**Comment by ussjohnjay** [comment]
Finally, this one attempts to show all information without the need for popups. We're getting really big now, but if you're going to require scrolling on mobile, it might as well show everything. Nevertheless, to keep it compact as possible, the recommendations are split into 2 columns with each skill getting its own row (and the skill icon now displayed to help clarify that). This view also matches the "cards" used to display other info about the voyage.

320-cards

All thoughts and suggestions are welcome!

**Comment by joshurtree** [comment]
Are these coded or did you do it some other way? If it is the former we could implement them all side by side to see how they each work on various platforms.

**Comment by ussjohnjay** [comment]
> Are these coded or did you do it some other way? If it is the former we could implement them all side by side to see how they each work on various platforms.

That's a good idea. Options 2 and 3 are coded, though neither has been optimized for mobile and option 3 is pretty sloppily written all around. I don't have time to make proper versions at the moment, but I've attached the two versions here if you want to figure that out. Otherwise I'll try to do this under a new PR later this weekend.

[voyagestats-tableavatars.tsx.txt](https://github.com/stt-datacore/website/files/7695809/voyagestats-tableavatars.tsx.txt)
[voyagestats-cards.tsx.txt](https://github.com/stt-datacore/website/files/7695810/voyagestats-cards.tsx.txt)

**Comment by ussjohnjay** [comment]
Moved all the changes here to a clean branch #377. This one's long overdue, so hopefully a clean branch will build a little easier.

**Pull request closed without merging**
