### PR TITLE
Added chart to voyage estimates.

### PR DESCRIPTION
**Pull request by joshurtree**

### CODE REVIEW

**Comment by AlexCPU** [comment]
Deployed successfully

            
Latest commit: | 62387b9
-- | --
Status: | ✅&nbsp; Deploy successful!
Preview URL: | https://51ea140f.website-i3mu.pages.dev


<p><a href="https://dash.cloudflare.com/?to=/:account/pages/view/website/51ea140f-0852-4717-ae85-de52a3043463" rel="nofollow">View logs</a></p>

**Comment by AlexCPU** [comment]
@ussjohnjay can you explain what the dotted line is on the graph output?
image

**Comment by joshurtree** [comment]
What platform is that on? It works fine on the desktop but I get the same effect on android.

**Comment by AlexCPU** [comment]
> 
> 
> What platform is that on? It works fine on the desktop but I get the same effect on android.

That was from Chrome on Win 10

**Comment by AlexCPU** [comment]
I'm seeing the same behaviour on both Firefox and Chrome.  Edge has a different bug where it seems to crash out giving a blank screen, but that bug exists in production as well!

**Comment by joshurtree** [comment]
Hopefully they should be gone now. All I wanted was to add tooltips but it seems there are some bugs with the library we use to create the charts.

**Review by AlexCPU — APPROVED** [review]

**Pull request merged**
